### ISSUE TITLE
Get GameObject Member> LocalOrientation and World orientation returns <0,0,0>..

### ISSUE THREAD

**Issue by vuniverse** [thepgi/bge-logic-nodes-add-on#4]
OK this is complicated. So i added file.
Get GameObject Member> LocalOrientation and World orientation parameters xyz returns 0 all the time.
If i use "Vector" to split orientation always each value reported 0
If i use "Vector 4" to split orientation always each value reported 0 unless i try to get W value.
If i try to get W value ( connecting exit node of W to something ) this time all returns nothing .. Even not changing textboxes.
If i unplug W. Then x y z turns to zero again..
I attach the file so you can test .

**Comment by vuniverse** [comment]
FILE : 
[Local orientaion reported empty.zip](https://github.com/thepgi/bge-logic-nodes-add-on/files/442936/Local.orientaion.reported.empty.zip)

**Comment by thepgi** [comment]
The Local Orientation is a 3x3 Matrix, if you pass it to a Vector node you only get the first four components of it. There is an Orientation node in the Math group to deal with orientation values.

**Comment by vuniverse** [comment]
Isn't orientation a quaternion ? I guessed so .. that's where i am lost i guess. O.O  I searched the web for orientation and could not find something. when i plug the orientation value to orientation node and get values  I get values. I am lost.. Do you suggest some page i can read about this ?

**Comment by thepgi** [comment]
That LocalOrientation node points to this game object field:

https://www.blender.org/api/blender_python_api_2_77a_release/bge.types.KX_GameObject.html?highlight=localorientation#bge.types.KX_GameObject.localOrientation

Unfortunately there's no way I know of to add to the add-on some sort of contextual documentation, so that the user would know exactly what that "orientation" output does. Common user interfaces do that with a small ? button near the control. I could add this help button but I haven't figured out a way to display readable information to the user. That's a missing corner stone in making the addon itself really usable.

**Comment by vuniverse** [comment]
thank you pgi. I will stick with radians and walksarounds for now ..I will check this and more.. At least now i have radians. I can understand them ..
